alpha/alpha/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('takim/',include('takim.urls')),
    path("accounts/", include("django.contrib.auth.urls")),  # new
    #path('account/', include('account.urls')),
    #path('summernote/', include('django_summernote.urls')),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

alpha/main/urls.py
from django.urls import path
from .views import Basvuru, basvuru_basari,iletisim,blog_detail,landing,kvkk
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [    
   
    path('', landing, name='index'),
    path('basvuru/', Basvuru.as_view(), name='basvuru'),
    path('iletisim/', iletisim, name='iletisim'),
    path('basvuru/basvuru_basari/', basvuru_basari, name='basvuru_basari'),
    path('blog/<slug:slug>/', blog_detail, name='blog_detail'),
    path('kvkk/', kvkk, name='kvkk'),

  
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alpha/main/models.py
from django.db import models

from django.urls import reverse
from django.core.validators import RegexValidator
from django.conf import settings
from django.utils.text import slugify
# Create your models here.

ANTRONER_CHOICES = (
    ("BANT", "Baş Antrenor"),
    ("ANT","Antrenor"),
    ("DYT","Diyetisyen"),
    ( "PSK","Psikolog"),

)
BLOG_CHOICES = (
    ("BLOG", "Blog"),
    ("DUYURU","Duyuru"),
)

class Antrenor (models.Model):
    adi=models.CharField(max_length=30)
    soyadi=models.CharField(max_length=30)
    unvan=models.TextField(choices=ANTRONER_CHOICES,default='ANT')
    resim=models.ImageField(upload_to='media/')
    ozet=models.TextField()
    ozgecmis=models.TextField()
    telefon=models.CharField(max_length=10)
    instagram=models.CharField(max_length=50)
    aktif=models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.adi+' '+ self.soyadi
    def get_absolute_url(self):
        return reverse("antrenor_list", kwargs={"id": self.id})
    

class Branslar (models.Model):
    brans= models.CharField(max_length=50)
    ozet=models.TextField()
    aciklama=models.TextField()
    resim=models.ImageField(null=True,blank=True)
    aktif=models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.brans

    def get_absolute_url(self):
        return reverse("brans_detail", kwargs={"id": self.id})

class InstagramPost(models.Model):
    baslik=models.CharField(max_length=100, default='Fk Alpha Academy')
    link=models.TextField()
    created_date=models.DateTimeField(auto_now_add=True)
    aktif=models.BooleanField(default=True)

    def __str__(self):
        return self.baslik + '--'+str(self.created_date)

    class Meta:
        ordering = ["-created_date"]


class Blog (models.Model):
    tur=models.TextField(choices=BLOG_CHOICES,default='BLOG')
    baslik=models.CharField(max_length=100)
    metin=models.TextField()
    resim=models.ImageField(null=True,blank=True)
    slug=models.SlugField(unique=True)
    aktif=models.BooleanField(default=True)
    created_date=models.DateTimeField(auto_now_add=True)
    author=models.ForeignKey(Antrenor,on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.baslik
    class Meta:
        ordering=["-created_date"]
    def get_absolute_url(self):
        return reverse("blog_detail", kwargs={"slug": self.slug})
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.baslik)
        super().save(*args, **kwargs)
    





KAYNAK_CHOICES = (
    ("INS", "Instagram"),
    ("INT","Internet"),
    ("TAV","Tavsiye"),
    ("DGR","Diğer"),
)
BEKLENTI_CHOICES = (
    ("OGR", "Yüzmeyi Öğrenmek"),
    ("TEK", "Stilli Yüzmek"),
    ("INT","Spor Yapmak"),
    ("TAV","Profosyonel Sporcu Olmak"),
    ("DGR","Diğer"),
)

DERS_CHOICES = (
    ("0", "Hiç Ders Almadı"),
    ("1", "Bir yıla kadar"),
    ("3","Bir yıl üç yıl"),
    ("4","Üç yıldan fazla"),
)
GRUP_CHOICES = (
    ("OZL", "Özel Ders"),
    ("GRP", "Grup Dersi"),
    ("TKM","Takım"),
)


class Basvuru (models.Model):
    adi=models.CharField(max_length=50)
    dogum_yili=models.IntegerField()
    boy=models.IntegerField()
    kilo=models.IntegerField()
    ayak=models.IntegerField()
    veli=models.CharField(max_length=50)
    phone_regex = RegexValidator(regex=r'^5.*$', message="Telefon numarası formatı: '+530 555 5555'")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # Validators should be a list
    kaynak=models.TextField(choices=KAYNAK_CHOICES)
    ders_suresi=models.TextField(choices=DERS_CHOICES)
    beklenti=models.TextField(choices=BEKLENTI_CHOICES)
    ders_turu=models.TextField(choices=GRUP_CHOICES)
    created_date=models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return  self.adi
    def get_absolute_url(self):
        return reverse("basvuru_detail", kwargs={"id": self.pk})
    

alpha/main/forms.py
from django import forms
from .models import Basvuru


class BransEkle(forms.Form):
    brans= forms.CharField(max_length=30)
    ozet=forms.TextInput()
    aciklama=forms.TextInput()
    aktif=forms.BooleanField()

class BasvuruForm(forms.ModelForm):
    class Meta:
        model=Basvuru
        fields="__all__"
        labels={'veli':'Adını Soyadınız ? (Veli)',
                'phone_number':'Telefon Numaranız ?',
                'adi':'Sporcunun Adı Soyadı ?',
                'kaynak':'Bizi nereden tanıyorsunuz ?',
                'ayak':'Ayakkabı numarası ?',
                'ders_suresi':'Daha önce yüzme dersi aldınız mı ?',
                'beklenti':'Yüzme sporunda hedefiniz nedir ?',
                'ders_turu':'Bizden ne tür bir hizmet bekliyorsunuz ?',
                }

    def __init__(self, *args, **kwargs):

        add_class="""class='bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500'>"""
        super(BasvuruForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = add_class

alpha/main/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Branslar,Antrenor,InstagramPost,Blog,Basvuru
from .forms import BasvuruForm
from django.views.generic import CreateView,UpdateView


from django.shortcuts import get_object_or_404

def landing(request):
    brans_list=Branslar.objects.filter(aktif=True)
    instagram_list=InstagramPost.objects.filter(aktif=True)[:3]
    antrenor_list=Antrenor.objects.filter(aktif=True).order_by('soyadi')
    duyuru_list=Blog.objects.filter(tur='DUYURU',aktif=True)[:20]
    blog_list=Blog.objects.filter(tur='BLOG',aktif=True)[:6]
    return render(request, 'landing.html',{'brans_list':brans_list,
                                         'instagram_list':instagram_list,
                                         'antrenor_list':antrenor_list,
                                         'duyuru_list':duyuru_list,
                                         'blog_list':blog_list
                                         })
def index(request):
    brans_list=Branslar.objects.filter(aktif=True)
    instagram_list=InstagramPost.objects.filter(aktif=True)[:3]
    antrenor_list=Antrenor.objects.filter(aktif=True).order_by('soyadi')
    duyuru_list=Blog.objects.filter(tur='DUYURU',aktif=True)
    blog_list=Blog.objects.filter(tur='BLOG',aktif=True)[:4]
    return render(request, 'index.html',{'brans_list':brans_list,
                                         'instagram_list':instagram_list,
                                         'antrenor_list':antrenor_list,
                                         'duyuru_list':duyuru_list,
                                         'blog_list':blog_list
                                         })



# Create your views here

def iletisim(request):
    return render(request,'iletisim.html')

class Basvuru (CreateView):
    model= Basvuru
    form_class=BasvuruForm
    success_url = 'basvuru_basari'

def basvuru_basari(request):
    return render(request,'main/basvuru_basari.html')

def blog_detail (request,slug):
    blog= get_object_or_404(Blog,slug=slug)
    blog_list=Blog.objects.filter(tur='BLOG') [:10]
    return render(request,'blog_detail.html',{'blog':blog,
                                              'blog_list':blog_list})

def kvkk (request):
    return render(request,'kvkk.html')

alpha/main/templates/partials/new/animate_custom.html
<section class=" "
    style=" background-image: url('media/bg_black.jpg'); background-repeat: no-repeat; background-size:cover; ">

    <div class="text-container">
        <div>#disiplin</div>
        <div>#takım ruhu</div>
        <div>#rekabet</div>
        <div>#başarı</div>
        <div>#çalışma</div>
        <div>#gelecek</div>
        <div>#sağlık</div>
        <div>#antrenman</div>
    </div>
    <div class="absolute inset-0 flex justify-center items-center z-10">
        <img class="h-3/6 opacity-40 rounded-3xl animate-pulse " src="media/logo.jpeg" alt="">

    </div>


</section>

alpha/main/templates/partials/new/basvur.html
<section class=" bg-gray-200 mt-20">


    <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6 ">
      
        <div class="mx-auto max-w-screen-sm text-center mb-8 lg:mb-16 bg-gray-300 rounded-lg">
            <h2 class="mb-4 pt-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Başvuru</h2>
            <p class="font-light text-gray-700 lg:mb-8 text-xl dark:text-gray-400">
                Aramıza katılmak istiyorsan kontenjanlarımız dolmadan hemen başvur.</p>
                
                  <div class="flex justify-center pb-4 ">
                    <a href="{% url 'basvuru' %}">
                    <button type="submit" class="text-white  bg-gray-800 min-h-20 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-lg px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700">Başvuru Formu</button>
                  </a>
                  </div>
               
        </div>


    </div>
</section>

alpha/main/templates/partials/new/block_antrenor.html
<section class=" bg-gray-200 dark:bg-gray-900 mt-10">
    <div class="px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6 ">
        <div class="mx-auto max-w-screen-sm text-center mb-8 lg:mb-16">
            <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Antrenörlerimiz</h2>
            <p class="font-light text-gray-500 lg:mb-16 sm:text-xl dark:text-gray-400">
                Her sporcunun uzun vadeli atletik gelişimi için en iyi eğitimi ve koçluğu almasını sağlayan,
                ulusal çapta örnek bir kulüp olmak için yorulmadan çalışan ekibimizle tanışın</p>
        </div> 
        <div class="grid gap-8 mb-6 lg:mb-16 md:grid-cols-2">
            {% for antrenor in antrenor_list %}
            
           
            <div class="items-center bg-gray-50 rounded-lg shadow sm:flex dark:bg-gray-800 dark:border-gray-700">
                <a href="#">
                    <img class="w-full rounded-lg sm:rounded-none sm:rounded-l-lg"
                     src="{{antrenor.resim.url}}" alt="{{antrenor}}">
                </a>
                <div class="p-5 ">
                    <h3 class="text-xl font-bold tracking-tight text-gray-900 dark:text-white">
                        <a href="#">{{antrenor}}</a>
                    </h3>
                    <span class="text-gray-500 dark:text-gray-400">{{antrenor.get_unvan_display}}</span>
                    <p class="mt-3 mb-4 font-light text-gray-500 dark:text-gray-400 text-xs">{{antrenor.ozet|safe|title}}</p>
                    <ul class="flex space-x-4 sm:mt-2">
                        <li>
                            <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path fill-rule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z" clip-rule="evenodd" /></svg>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" /></svg>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" /></svg>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path fill-rule="evenodd" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10c5.51 0 10-4.48 10-10S17.51 2 12 2zm6.605 4.61a8.502 8.502 0 011.93 5.314c-.281-.054-3.101-.629-5.943-.271-.065-.141-.12-.293-.184-.445a25.416 25.416 0 00-.564-1.236c3.145-1.28 4.577-3.124 4.761-3.362zM12 3.475c2.17 0 4.154.813 5.662 2.148-.152.216-1.443 1.941-4.48 3.08-1.399-2.57-2.95-4.675-3.189-5A8.687 8.687 0 0112 3.475zm-3.633.803a53.896 53.896 0 013.167 4.935c-3.992 1.063-7.517 1.04-7.896 1.04a8.581 8.581 0 014.729-5.975zM3.453 12.01v-.26c.37.01 4.512.065 8.775-1.215.25.477.477.965.694 1.453-.109.033-.228.065-.336.098-4.404 1.42-6.747 5.303-6.942 5.629a8.522 8.522 0 01-2.19-5.705zM12 20.547a8.482 8.482 0 01-5.239-1.8c.152-.315 1.888-3.656 6.703-5.337.022-.01.033-.01.054-.022a35.318 35.318 0 011.823 6.475 8.4 8.4 0 01-3.341.684zm4.761-1.465c-.086-.52-.542-3.015-1.659-6.084 2.679-.423 5.022.271 5.314.369a8.468 8.468 0 01-3.655 5.715z" clip-rule="evenodd" /></svg>
                            </a>
                        </li>
                    </ul>
                </div>
            </div> 
            {% endfor %}
        </div>  
    </div>
  </section>

alpha/main/templates/partials/new/block_blog.html
<section class="relative  items-center  bg-gray-200 dark:bg-gray-900 mt-10">
    

  <!-- Blog  -->

        <div class="items-center">
            <section class=" bg-gray-200 dark:bg-gray-900">
                <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6">
                    <div class="mx-auto max-w-screen-sm text-center lg:mb-16 mb-8">
                        <h2 class="mb-4 text-3xl lg:text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Bülten</h2>
                        <p class="font-light text-gray-500 sm:text-xl dark:text-gray-400">Sizler için faydalı olacağını düşündüğümüz yazılarımızın keyfini çıkarın</p>
                    </div> 
                    <div class="grid gap-8 lg:grid-cols-4">
                        {% for blog in blog_list  %}
                        <div>
                       
                        <article class="p-6  bg-gray-100 rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
                            <div class="flex justify-between items-center mb-5 text-gray-500">
                                <span class="bg-primary-100 text-primary-800 text-xs font-medium inline-flex items-center px-2.5 py-0.5 rounded dark:bg-primary-200 dark:text-primary-800">
                                    <svg class="mr-1 w-3 h-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2 6a2 2 0 012-2h6a2 2 0 012 2v8a2 2 0 01-2 2H4a2 2 0 01-2-2V6zM14.553 7.106A1 1 0 0014 8v4a1 1 0 00.553.894l2 1A1 1 0 0018 13V7a1 1 0 00-1.447-.894l-2 1z"></path></svg>
                                    {{blog.tur}}
                                </span>
                                <span class="text-sm">{{blog.created_date}}</span>
                            </div>
                            <h2 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><a href="#">{{blog.baslik|title}}</a></h2>
                            <p class="mb-5 text-gray-900 dark:text-gray-400">{{blog.metin|safe|truncatewords:20}}</p>
                            <div class="flex justify-between items-center">
                                <div class="flex items-center space-x-4">
                                    <img class="w-7 h-7 rounded-full" src="media/logo1.jpeg" alt="Jese Leos avatar" />
                                    <span class="font-medium dark:text-white">
                                        {{blog.author.adi}} {{blog.author.soyadi}}
                                    </span>
                                </div>
                                <a href="{{blog.get_absolute_url}}" class="inline-flex items-center font-medium text-primary-600 dark:text-primary-500 hover:underline">
                                    Devami
                                    <svg class="ml-2 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                                </a>
                            </div>
                        </article> 
                    </div>
                        {% endfor %}
                    </div>  
                </div>
              </section>
        
    </div>
</section>

alpha/main/templates/partials/new/block_brans.html
<section class=" bg-gray-200 mt-10">


    <div class="  px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6 ">
      
        <div class="mx-auto max-w-screen-sm text-center mb-8 lg:mb-16">
            <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Branşlarımız</h2>
            <p class="font-light text-gray-500 lg:mb-16 sm:text-xl dark:text-gray-400">
                Sporcuya özel planlanmış, uzun yıllar deneyimle geliştirilmiş programlarımız</p>
                

               
        </div>



            <div class="container max-w-screen-xl mx-auto px-4 py-6">
    
                <div class="grid grid-cols-1  lg:grid-cols-3 gap-4">
                    {% for brans in brans_list %}
                    <div class="">
                        <div class="relative flex flex-col min-w-0 break-word w-full mb-6 shadow-lg rounded-lg bg-gray-600">
                          <img alt="..." 
                          src="{{brans.resim.url}}" class="w-full align-middle rounded-t-lg max-h-48">
                          <blockquote class="relative p-8 mb-4">
                            <svg preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 583 95" class="absolute left-0 w-full block" style="height: 95px; top: -94px;">
                              <polygon points="-30,95 583,95 583,65" class="text-gray-600 fill-current"></polygon>
                            </svg>
                            <h4 class="text-xl font-bold text-white">
                              {{brans.brans}}
                            </h4>
                            <p class="text-md font-light mt-2 text-white">
                                {{brans.aciklama|safe}}
                            </p>
                          </blockquote>
                                          
                  <div class="flex justify-center pb-4 ">
                    <a href="{% url 'basvuru' %}">
                    <button type="submit" class="text-white  bg-gray-800  hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-lg px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700">Başvuru Formu</button>
                  </a>
                  </div>
                        </div>
                      </div>
                    {% endfor %}
                </div>
    
            </div>

    </div>
</section>

alpha/main/templates/partials/new/block_instagram.html
<section class="bg-white dark:bg-gray-900 mt-20">
    <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6 ">
        <div class="mx-auto max-w-screen-sm text-center mb-8 lg:mb-16">
            <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Bizi Takip Edin</h2>

        </div> 

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mx-auto ">
            {% for post in instagram_list %}
           
                {{post.link|safe}}
           
            {% endfor %}
        </div>
    </div>

</section>

alpha/main/templates/partials/new/carousel.html
<section class="relative  items-center bg-gray-200 dark:bg-gray-900 mt-20">
    <div class="grid grid-cols-1 md:grid-cols-2">
        <div class="mx-auto max-w-screen-sm text-center mt-6 mb-6 lg:mb-8">
            <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Bizden Haberler
            </h2>
        </div>
        <div class="items-center ">




            <div id="controls-carousel" class="relative w-full" data-carousel="slide">
                <!-- Carousel wrapper -->
                <div class="relative overflow-hidden rounded-lg  h-56 md:h-96">
                     <!-- Item 1 -->
                     {% for duyuru in duyuru_list  %}
                                     
                    <div class="hidden duration-700 ease-in-out" data-carousel-item>
                        <img src="{{duyuru.resim.url}}" class="absolute object-scale-down h-full rounded-2xl -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
                    </div>
                    {% endfor %}
                </div>
                <!-- Slider controls -->
                <button type="button" class="absolute top-0 start-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-prev>
                    <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
                        <svg class="w-4 h-4 text-white dark:text-gray-800 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 1 1 5l4 4"/>
                        </svg>
                        <span class="sr-only">Previous</span>
                    </span>
                </button>
                <button type="button" class="absolute top-0 end-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-next>
                    <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
                        <svg class="w-4 h-4 text-white dark:text-gray-800 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                        </svg>
                        <span class="sr-only">Next</span>
                    </span>
                </button>
            </div>
            

        </div>
  <!-- Blog  -->


    </div>
</section>