alpha/alpha/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('takim/',include('takim.urls')),
    path("accounts/", include("django.contrib.auth.urls")),  # new
    #path('account/', include('account.urls')),
    #path('summernote/', include('django_summernote.urls')),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

alpha/main/urls.py
from django.urls import path
from .views import Basvuru, basvuru_basari,iletisim,blog_detail,landing,kvkk
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [    
   
    path('', landing, name='index'),
    path('basvuru/', Basvuru.as_view(), name='basvuru'),
    path('iletisim/', iletisim, name='iletisim'),
    path('basvuru/basvuru_basari/', basvuru_basari, name='basvuru_basari'),
    path('blog/<slug:slug>/', blog_detail, name='blog_detail'),
    path('kvkk/', kvkk, name='kvkk'),

  
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alpha/takim/urls.py
from django.urls import path
from .views import takim_list,CreateTakim,sporcu_ekle,updateSporcu,sporcudetay,sporcukayit,sporcu_list,dashboard,odeme_ekle

urlpatterns = [
    path('',dashboard,name='takim'),
    path('sporcular/',sporcu_list,name='sporcular'),
    path('takimlar/',takim_list,name='takim_list'),
    path('sporcukayit/',sporcukayit,name='sporcukayit'),
    path('sporcudetay/<uuid:s_uuid>/',sporcudetay,name='sporcudetay'),
    path('takimekle/',CreateTakim.as_view(),name='takimekle'),
    path('sporcuekle/',sporcu_ekle,name='sporcuekle'),
    path('sporcupdate/<uuid:s_uuid>/<str:detay>',updateSporcu,name='sporcupdate'),
    path('odeme/',odeme_ekle,name='odeme'),
    
]

alpha/takim/models.py
from django.db import models
from django.urls import reverse
from PIL import Image
import uuid
from django.conf import settings
# Create your models here.
class Takim (models.Model):
    adi=models.CharField()
    renk=models.CharField(default='red')
    aktif=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.adi



YES_NO= (
    ("Evet", "Evet"),
    ("Hayır","Hayır"),

)

unvan=models.TextField(choices=YES_NO,default='Hayır')
class Sporcu(models.Model):
    resim=models.ImageField(null=True,blank=True,upload_to='media/')
    adi=models.CharField()
    soyadi=models.CharField()
    dogum_tarihi=models.DateField()
    okul=models.CharField()
    telefon=models.CharField(null=True,blank=True)
    veli=models.CharField()
    veli_telefon=models.CharField()
    veli_eposta=models.EmailField()
    takim=models.ForeignKey(Takim,on_delete=models.CASCADE ,null=True)
    aktif=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    s_uuid=models.UUIDField(default=uuid.uuid4, unique=True,
          primary_key=False, editable=False,null=True)

    kronik_hastalik=models.CharField(null=True,blank=True)
    sakatlik_ameliyat=models.CharField(null=True,blank=True)
    kullanilan_ilac=models.CharField(null=True,blank=True)
    alerji=models.CharField(null=True,blank=True)
    kalp=models.CharField(null=True,blank=True)
    sosyal=models.CharField(null=True,blank=True)
    kalabalik=models.CharField(null=True,blank=True)
    dikkat=models.CharField(null=True,blank=True)
    komut=models.CharField(null=True,blank=True)
    iliski=models.CharField(null=True,blank=True)


    yuzme_gecmisi=models.CharField(null=True,blank=True)
    yuzme_bilgisi=models.CharField(null=True,blank=True)
    derinlik=models.TextField(choices=YES_NO,default='Hayır')
    su_korkusu=models.TextField(choices=YES_NO,default='Hayır')
    denizde_yuzme=models.TextField(choices=YES_NO,default='Evet')
    neden_yuzme=models.CharField(null=True,blank=True)
    istek_yuzme=models.CharField(null=True,blank=True)
    vade_yuzme=models.CharField(null=True,blank=True)

    ulasim=models.CharField(null=True,blank=True)
    katilim=models.CharField(null=True,blank=True)
    diger_spor=models.CharField(null=True,blank=True)
    aile_not=models.TextField(null=True,blank=True)
    antrenor_not=models.TextField(null=True,blank=True)

    def get_absolute_url(self):
        return reverse("sporcudetay", kwargs={"s_uuid": self.s_uuid})

    def __str__(self):
        return self.adi+' '+ self.soyadi

    def get_dogum_yili(self):
        return self.dogum_tarihi.year

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        # Resize profile image to 150x150
        if self.resim:
            img = Image.open(self.resim.path)
            width, height = img.size
            
            bolen=4
            if width>3000:
                bolen=10
            if width>1000:
                img = img.resize((img.width // bolen, img.height // bolen))
                img.save(self.resim.path)


ODEME_TURU= (
    ("Uyelik", "Uyelik"),
    ("MALZEME", "Malzeme"),
)
MALZEME_TURU= (
    ("T-shirt", "T-shirt"),
    ("Esofman", "Esofman"),
    ("Bone", "Bone"),
    ("Bere", "Bere"),
    ("Corap", "Corap"),
)


AYLAR= (
    (1, "Ocak"),
    (2, "Şubat"),
    (3, "Mart"),
    (4, "Nisan"),
    (5, "Mayıs"),
    (6, "Haziran"),
    (7, "Temmuz"),
    (8, "Ağustos"),
    (9, "Eylül"),
    (10, "Ekim"),
    (11, "Kasım"),
    (12, "Aralık"),

)

class Odeme(models.Model):
    sporcu=models.ForeignKey(Sporcu,on_delete=models.CASCADE)
    odeme_turu=models.CharField(choices=ODEME_TURU)
    malzeme_turu=models.CharField(choices=MALZEME_TURU,blank=True,null=True)
    yil=models.IntegerField()
    ay=models.IntegerField(choices=AYLAR)
    odendi=models.BooleanField(default=False)
    create_user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now=True)


    class Meta:
        ordering = ["-yil","-ay"]

    def __str__(self):
        return self.sporcu.adi+'-'+str(self.created)+'-'+str(self.odeme_turu)+'-'+str(self.ay)

alpha/takim/forms.py
from django import forms
from.models import Takim,Sporcu,Odeme

class FormTakim(forms.ModelForm):
    class Meta:
        model=Takim
        fields='__all__'
    def __init__(self, *args, **kwargs):

        add_class='w-full px-5 py-1 text-gray-700 bg-gray-200 rounded'
        super(FormTakim, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = add_class

class FormSporcu(forms.ModelForm):
    class Meta:
        model=Sporcu

        fields = ('resim','adi','soyadi','dogum_tarihi','okul','telefon','veli','veli_telefon','veli_eposta','takim')
        widgets = {
      'dogum_tarihi': forms.DateInput(attrs={ 'type': 'date',})
   }
    def __init__(self, *args, **kwargs):

        add_class='w-full px-5 py-1 text-gray-700 bg-gray-200 rounded'
        super(FormSporcu, self).__init__(*args, **kwargs)
        self.fields['takim'].required = False
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = add_class
        



class FormSaglik(forms.ModelForm):
    class Meta:
        model=Sporcu
        fields = ('kronik_hastalik','sakatlik_ameliyat','kullanilan_ilac','alerji','kalp','sosyal','kalabalik','komut')
    def __init__(self, *args, **kwargs):

        add_class='w-full px-5 py-1 text-gray-700 bg-gray-200 rounded'
        super(FormSaglik, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = add_class

BRANS_CHOICES = {
    "Serbest": "Serbest",
    "Sırtüstü": "Sırtüstü",
    "Kelebek": "Kelebek",
    "Kurbağalama": "Kurbağalama",
}

class FormYuzme(forms.ModelForm):
   
    class Meta:
        model=Sporcu
        fields = ('yuzme_gecmisi','yuzme_bilgisi','derinlik','su_korkusu','denizde_yuzme','neden_yuzme','istek_yuzme','vade_yuzme','diger_spor')
      
    def __init__(self, *args, **kwargs):

        add_class='w-full px-5 py-1 text-gray-700 bg-gray-200 rounded'
        super(FormYuzme, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = add_class

class FormUlasim(forms.ModelForm):
    class Meta:
        model=Sporcu
        fields = ('aile_not','antrenor_not')
    def __init__(self, *args, **kwargs):

        add_class='w-full px-5 py-1 text-gray-700 bg-gray-200 rounded'
        super(FormUlasim, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = add_class


class FormSporcuFull(forms.ModelForm):
    class Meta:
        model=Sporcu

        fields=('resim','adi','soyadi','dogum_tarihi','okul','telefon','veli','veli_telefon','veli_eposta','takim',
                'kronik_hastalik','sakatlik_ameliyat','kullanilan_ilac','alerji','kalp','sosyal','kalabalik','komut',
                'yuzme_gecmisi','yuzme_bilgisi','derinlik','su_korkusu','denizde_yuzme','neden_yuzme','istek_yuzme','vade_yuzme',
                'diger_spor','aile_not','antrenor_not'
                )
        widgets = {
      'dogum_tarihi': forms.DateInput(attrs={ 'type': 'date',}),
      'telefon': forms.TextInput(attrs={ 'type': 'tel',}),

   }
    def __init__(self, *args, **kwargs):

        add_class='w-full px-5 py-1 text-gray-700 bg-gray-200 rounded'
        super(FormSporcuFull, self).__init__(*args, **kwargs)
        self.fields['takim'].required = False
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = add_class

class FormOdeme(forms.ModelForm):
    class Meta:
        model=Odeme
        fields='__all__'

    def __init__(self, *args, **kwargs):

        add_class='w-full px-5 py-1 text-gray-700 bg-gray-200 rounded'
        super(FormOdeme, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = add_class

alpha/takim/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Takim,Sporcu,Odeme,AYLAR
from .forms import FormSporcu,FormTakim,FormSaglik,FormYuzme,FormSporcuFull,FormUlasim,FormOdeme
from django.views.generic import CreateView,UpdateView,DeleteView
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from django.db.models.functions import ExtractYear
from datetime import date

# Create your views here.

@login_required(login_url='/')
def  dashboard(request):
    takimlar = Takim.objects.annotate(number_of_sporcu=Count('sporcu'))
    sporcular=Sporcu.objects.all().order_by('-id')[:10]
    form=FormTakim
    sporcuform=FormSporcu
    return render(request,'dashboard.html',{"takimlar":takimlar,'sporcular':sporcular,'form':form,'sporcuform':sporcuform})


@login_required(login_url='/')
def sporcu_list(request):
    takimlar = Takim.objects.annotate(number_of_sporcu=Count('sporcu'))
    sporcular=Sporcu.objects.all().order_by('-id')[:10]
    form=FormTakim
    sporcuform=FormSporcuFull


    return render(request,'sporcular.html',{"takimlar":takimlar,'sporcular':sporcular,'form':form,'sporcuform':sporcuform})

@login_required(login_url='/')
def takim_list(request):
    takimlar = Takim.objects.annotate(number_of_sporcu=Count('sporcu'))
    sporcular=Sporcu.objects.all().values('dogum_tarihi__year','takim__adi','takim__renk','adi','soyadi','takim__adi','s_uuid')
    takim_yas = sporcular.values('dogum_tarihi__year','takim__adi','takim__renk').annotate(sayi=Count('id'))
    print(sporcular)
   

    return render(request,'takimlar.html',{"takimlar":takimlar,'takim_yas':takim_yas,'sporcular':sporcular})

def modal(request):
    takimlar = Takim.objects.annotate(number_of_sporcu=Count('sporcu'))
    sporcular=Sporcu.objects.all().order_by('-id')[:4]
    return render(request,'modal.html',{"takimlar":takimlar,'sporcular':sporcular})


def sporcudetay(request,s_uuid):
    bugun=date.today()
    sporcu=get_object_or_404(Sporcu,s_uuid=s_uuid)
    odemeler=Odeme.objects.filter(sporcu=sporcu,odeme_turu='Uyelik')
    odenmemis=False
    odeme_check=[]
    for ay in AYLAR:
        if ay[0]<=bugun.month:
            if odemeler.filter(ay=ay[0],odendi=True):
                odeme_check.append({'ay':ay[1],'odeme_tarihi':odemeler.filter(ay=ay[0]).first().updated})
            else:
                odeme_check.append({'ay':ay[1],'odeme_tarihi':None})
                odenmemis=True
    odeme_check.reverse()
    
    if odemeler.filter(ay=bugun.month):
        odenmeyen=None
    else:
        odenmeyen=AYLAR[bugun.month][1] 

    formSaglik=FormSaglik(instance=sporcu)
    formYuzme=FormYuzme(instance=sporcu)
    formSporcu=FormSporcu(instance=sporcu)
    formUlasim=FormUlasim(instance=sporcu)

    
    kayit=True
    if request.COOKIES.get('s_uuid'):
        kayit=False


    response=render(request, 'sporcu_detay.html',{'sporcu':sporcu,
                                                  'odenmemis':odenmemis,
                                                  'odeme_check':odeme_check,
                                                  'formSaglik':formSaglik,'formYuzme':formYuzme,
                                                  'formSporcu':formSporcu,'formUlasim':formUlasim,
                                                  'kayit':kayit})
    response.set_cookie('s_uuid',sporcu.s_uuid)
    
    return response

class CreateTakim(CreateView):
    model=Takim
    form_class=FormTakim
    
def sporcu_ekle(request):
   if request.method == "POST":
       form = FormSporcuFull(request.POST,request.FILES)
       if form.is_valid():
           sporcu=form.save()
           return redirect('/takim/sporcudetay/'+str(sporcu.s_uuid))  # Adjust this to your post list view
       
   else:
       form = FormSporcu()
   return render(request, 'partials/modal_sporcu.html', {'form': form})

def updateSporcu(request,s_uuid,detay=None):
    sporcu = get_object_or_404(Sporcu, s_uuid = s_uuid)

    if request.method == 'POST':
        post=request.POST
        post = request.POST.copy() # to make it mutable
        if request.FILES == None:
            post['resim'] = sporcu.resim        
        form=FormSporcu(post,request.FILES,instance=sporcu)
        if detay=='saglik':
            form=FormSaglik(post,request.FILES,instance=sporcu)    
        if detay=='yuzme':
            
            form=FormYuzme(post,request.FILES,instance=sporcu)
        if detay=='ulasim':
            form=FormUlasim(post,request.FILES,instance=sporcu)
        print(form.is_valid())
        if form.is_valid():
            print('aaa')
            form.save()
            return  redirect('/takim/sporcudetay/'+str(s_uuid))
    else:
        sporcuform=FormSporcu(instance = sporcu)

    return render(request,'partials/modal_sporcu.html',{'sporcuform':sporcuform,'sporcu':sporcu})

def sporcukayit(request):
    form=FormSporcuFull
    s_uuid=request.COOKIES.get('s_uuid')
    if s_uuid:
        return redirect('sporcudetay', s_uuid=s_uuid)
    else:
        return render(request,'sporcu_kayit.html',{'form':form})
    
def saglik_ekle(request):
   if request.method == "POST":
       form = FormSporcu(request.POST,request.FILES)
       print(form)
       if form.is_valid():
           sporcu=form.save()
           return redirect('/takim/sporcudetay/'+str(sporcu.s_uuid))  # Adjust this to your post list view
       
   else:
       form = FormSporcu()
   return render(request, 'takim/sporcu_form.html', {'form': form})


def odeme_ekle(request):
    if request.method=='POST':
        data=request.POST
        sporcu=data.get('sporcu')
        odeme_turu='Uyelik'
        yil=data.get('yil')
        ay=data.get('ay')
        if Odeme.objects.filter(sporcu=sporcu,odeme_turu=odeme_turu,yil=yil,ay=ay):
            odeme_var=Odeme.objects.get(sporcu=sporcu,odeme_turu=odeme_turu,yil=yil,ay=ay)
            form=FormOdeme(request.POST,instance=odeme_var)
        else:
            form=FormOdeme(request.POST)
        if form.is_valid():
            form.save()

            return redirect('takim/')
    else:
        form=FormOdeme()
    return render(request,'odeme.html',{'form':form})
    

alpha/takim/templates/partials/modal_saglik.html
          <!--/Modal saglik Tabs-->
          
          <div class="flex flex-1 flex-col bg-gray-300 md:flex-row lg:flex-row ">
            <div class="mb-2  border-solid border-gray-300  rounded border shadow-sm w-full ">
        
                <div class="pt-3">
                    <button data-modal="saglikFormModal" class="modal-trigger bg-gray-500 hover:bg-gray-400 text-white text-xs  py-1 px-2 rounded">
                        Güncelle
                    </button>
                </div>
        
            </div>
            <div id="saglikFormModal" class="modal-wrapper">
                <div class="overlay close-modal"></div>
                <div class="modal modal-centered">
                    <div class="modal-content shadow-lg py-1">
                        <div class="border-b pb-3 pt-0 mb-4">
                           <div class="flex justify-between p-4 items-center">
                                Sağlık Bilgileri
                                <span class="close-modal cursor-pointer py-1 rounded-full bg-gray-100 hover:bg-gray-200">
                                    <i ><img class="h-6 w-6" src="https://img.icons8.com/?size=100&id=121477&format=png&color=000000" alt=""></i>
                                </span>
                           </div>
                        </div>
                        <div class="w-full max-w-lg">
                            <div class="leading-loose">
            <form method="post" action="{%url 'sporcupdate' sporcu.s_uuid 'saglik' %}" class="max-w-xl p-4 bg-white rounded shadow-xl">
                {% csrf_token %}     

                                                    <div class="mt-2">
                                            {{ formSaglik.kronik_hastalik.errors }}
                                            <label class="block text-sm text-gray-00" for="cus_name">Herhangi bir kronik rahatsızlığı var mı? (Astım, diyabet, epilepsi vb.)</label>
                                            {{ formSaglik.kronik_hastalik }}             
                                        </div>
                                            <div class="mt-2">
                                            {{ formSaglik.sakatlik_ameliyat.errors }}
                                            <label class="block text-sm text-gray-00" for="cus_name">Geçirilmiş ciddi sakatlık veya ameliyatlar (varsa yılı ve detayları)?</label>
                                            {{ formSaglik.sakatlik_ameliyat }}             
                                        </div>
                                            <div class="mt-2">
                                            {{ formSaglik.kullanilan_ilac.errors }}
                                            <label class="block text-sm text-gray-00" for="cus_name">Düzenli kullandığı ilaçlar var mı?</label>
                                            {{ formSaglik.kullanilan_ilac }}             
                                        </div>
                                            <div class="mt-2">
                                            {{ formSaglik.alerji.errors }}
                                            <label class="block text-sm text-gray-00" for="cus_name">Alerjik olduğu herhangi bir madde / ilaç / besin var mı?</label>
                                            {{ formSaglik.alerji }}             
                                        </div>
                                        <div class="mt-2">
                                            {{ formSaglik.kalp.errors }}
                                            <label class="block text-sm text-gray-00" for="cus_name">Kalp veya solunumla ilgili şikâyet yasadı mı?</label>
                                            {{ formSaglik.kalp }}             
                                        </div>
                  
                                        <div class="mt-2">
                                            {{ formSaglik.sosyal.errors }}
                                            <label class="block text-sm text-gray-00" for="cus_name">Sporcu içe dönük mü, dışa dönük mü?</label>
                                            {{ formSaglik.sosyal }}             
                                        </div>
                                        <div class="mt-2">
                                            {{ formSaglik.kalabalik.errors }}
                                            <label class="block text-sm text-gray-00" for="cus_name">Kalabalık ortamlarda rahat mı?</label>
                                            {{ formSaglik.kalabalik }}             
                                        </div>
                                        <div class="mt-2">
                                            {{ formSaglik.dikkat.errors }}
                                            <label class="block text-sm text-gray-00" for="cus_name"></label>
                                            {{ formSaglik.dikkat }}             
                                        </div>
                                        <div class="mt-2">
                                            {{ formSaglik.komut.errors }}
                                            <label class="block text-sm text-gray-00" for="cus_name">Komut almada zorlanır mı?</label>
                                            {{ formSaglik.komut }}             
                                        </div>
                                        <div class="mt-2">
                                            {{ formSaglik.iliski.errors }}
                                            <label class="block text-sm text-gray-00" for="cus_name"></label>
                                            {{ formSaglik.iliski }}             
                                        </div>
                <div class="mt-4">
                    <button class="px-4 py-1 text-white font-light tracking-wider bg-gray-900 rounded" type="submit">Kaydet</button>
                </div>
     
            </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    <!--/Modal saglik  Tabs-->

alpha/takim/templates/partials/modal_yuzme.html
<!--/Modal yuzme Tabs-->
          
          <div class="flex flex-1 flex-col md:flex-row lg:flex-row mx-2">
            <div class="mb-2   ">
        
                <div class="pt-3">
                    <button data-modal="yuzmeFormModal" class="modal-trigger bg-gray-500 hover:bg-gray-400 text-white text-xs  py-1 px-2 rounded">
                        Güncelle
                    </button>
                </div>
        
            </div>
            <div id="yuzmeFormModal" class="modal-wrapper">
                <div class="overlay close-modal"></div>
                <div class="modal modal-centered">
                    <div class="modal-content shadow-lg py-1">
                        <div class="border-b pb-3 pt-0 mb-4">
                           <div class="flex justify-between p-4 items-center">
                            <p class="text-gray-800 font-medium">Yüzme Bilgileri</p>
                                <span class="close-modal cursor-pointer py-1 rounded-full bg-gray-100 hover:bg-gray-200">
                                    <i ><img class="h-6 w-6" src="https://img.icons8.com/?size=100&id=121477&format=png&color=000000" alt=""></i>
                                </span>
                           </div>
                        </div>
                        <div class="w-full max-w-lg">
                            <div class="leading-loose">
            <form method="post" action="{%url 'sporcupdate' sporcu.s_uuid 'yuzme' %}" class="max-w-xl m-4 p-4 bg-white rounded shadow-xl">
                {% csrf_token %}
                
 
                <div class="mt-2">
                    {{ formYuzme.yuzme_gecmisi.errors }}
                    <label class="block text-sm text-gray-00" for="cus_name">Daha önce yüzme eğitimi aldı mı? Nerede ve ne kadar süreyle?</label>
                     {{ formYuzme.yuzme_gecmisi }}             
                </div>
        <div class="mt-2">
                    {{ formYuzme.yuzme_bilgisi.errors }}
                    <label class="block text-sm text-gray-00" for="cus_name">Hangi yüzme tekniklerini biliyor? (Serbest / Sırtüstü/ Kurbağalama /
            Kelebek)</label>
            
                                        
                        <div id="id_yuzme_bilgisi" class="w-full inline-flex justify-between text-gray-700 bg-gray-200 rounded">
                            <div>
                            <label for="id_yuzme_bilgisi_0"><input type="checkbox" name="yuzme_bilgisi" value="Serbest" class="  text-gray-700 bg-gray-200 rounded" id="id_yuzme_bilgisi_0">
                        Serbest</label>

                        </div>
                        <div>
                            <label for="id_yuzme_bilgisi_1"><input type="checkbox" name="yuzme_bilgisi" value="Sırtüstü" class=" text-gray-700 bg-gray-200 rounded" id="id_yuzme_bilgisi_1">
                        Sırtüstü</label>

                        </div><div>
                            <label for="id_yuzme_bilgisi_2"><input type="checkbox" name="yuzme_bilgisi" value="Kelebek" class="  text-gray-700 bg-gray-200 rounded" id="id_yuzme_bilgisi_2">
                        Kelebek</label>

                        </div><div>
                            <label for="id_yuzme_bilgisi_3"><input type="checkbox" name="yuzme_bilgisi" value="Kurbağalama" class="  text-gray-700 bg-gray-200 rounded" id="id_yuzme_bilgisi_3">
                        Kurbağalama</label>

                        </div>
                        </div>


                </div>
                                <div class="mt-2">
                    {{ formYuzme.derinlik.errors }}
                    <label class="block text-sm text-gray-00" for="cus_name">Derin suya girebiliyor mu?</label>
                     {{ formYuzme.derinlik }}             
                </div>
                                <div class="mt-2">
                    {{ formYuzme.su_korkusu.errors }}
                    <label class="block text-sm text-gray-00" for="cus_name">Suya atlama / batma korkusu yaşıyor mu?</label>
                     {{ formYuzme.su_korkusu }}             
                </div>
                                <div class="mt-2">
                    {{ formYuzme.denizde_yuzme.errors }}
                    <label class="block text-sm text-gray-00" for="cus_name">Havuz dışında denizde / gölde yüzme deneyimi oldu mu?</label>
                     {{ formYuzme.denizde_yuzme }}             
                </div>
                                                <div class="mt-2">
                    {{ formYuzme.neden_yuzme.errors }}
                    <label class="block text-sm text-gray-00" for="cus_name">Aile bu eğitimi neden aldırmak istiyor? (Hobi, öğrenme, lisansli yüzücü vb.)</label>
                     {{ formYuzme.neden_yuzme }}             
                </div>
                                            <div class="mt-2">
                    {{ formYuzme.diger_spor.errors }}
                    <label class="block text-sm text-gray-00" for="cus_name">Başka spor dallarıyla uğraşıyor mu? (Varsa günleri ve saatleri)</label>
                     {{ formYuzme.diger_spor }}             
                </div>
                                                <div class="mt-2">
                    {{ formYuzme.istek_yuzme.errors }}
                    <label class="block text-sm text-gray-00" for="cus_name">Sporcu bu eğitime ne kadar istekli? (Aile gözlemine göre)</label>
                     {{ formYuzme.istek_yuzme }}             
                </div>
                                                <div class="mt-2">
                    {{ formYuzme.vade_yuzme.errors }}
                    <label class="block text-sm text-gray-00" for="cus_name">Ailenin uzun vadeli beklentisi nedir?</label>
                     {{ formYuzme.vade_yuzme }}             
                </div>
          
    <div class="mt-4">
                    <button class="px-4 py-1 text-white font-light tracking-wider bg-gray-900 rounded" type="submit">Kaydet</button>
                </div>
     
            </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    <!--/Modal saglik  Tabs-->